spring.application.name=OpenScrum

spring.modulith.events.jdbc.schema-initialization.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/open-scrum
spring.datasource.username=open-scrum
spring.datasource.password=change-me
